### ISSUE TITLE
Is upload working for you reliably?

### ISSUE THREAD

**Issue by lalwanivikas** [eddyizm/insta_delete#1]
Hey man! thanks for writing this. 

I am unable to get the upload working as expected. Pulled some parts from https://github.com/ozkc/selenium-instagram-uploader but still no luck.

If it's working for you, then I will try debugging at my end first.

**Comment by eddyizm** [comment]
I just finished writing this yesterday. It was successfully tested and then I set it up as a cronjob and it ran successfully. This morning it failed. So I need to look into it. It could be a connection failure as I am not putting any waits, just a random sleep timer. What error are you getting?

**Comment by lalwanivikas** [comment]
Unable to find elements in the page. Then I plugged in some code from the other repo to pass that part. Now it failed at next step. BTW I am thinking of trying this to upload: https://stackoverflow.com/questions/8665072/how-to-upload-file-picture-with-selenium-python

**Comment by eddyizm** [comment]
Finding elements will continue to be the problem as Instagram changes their markup. I'll test manually when I get home.i know there is room for improvement on some elements, to make the xpath less rigid.

**Comment by eddyizm** [comment]
I just tested the script and it works as expected. Uploaded image smoothly. 
I did push the sleep time range floor up as my connection sometimes gets spotty. The element will not be found if the page is not loaded, that should go without saying.
```randrange(13,45)```

I'm also on lubuntu and using geckodriver. I just finished this script over the weekend so I haven't stubbed out the usage or swapped in variables for everyone else to plug. 

If you are having issues and want help, please post a detail stacktrace of your error message, the screenshot of where it is failing and the function where it goes sideways. 

I have a directory with two folders full of images I'm uploading, right now the schedule is once a day but I might try twice a day. If you fork and branch, it should work on your system but I suspect having a different OS will complicate things. 

cheers.
