### ISSUE TITLE
Its work?

### ISSUE THREAD

**Issue by fatmaindikass** [eddyizm/insta_delete#2]

**Comment by eddyizm** [comment]
the delete and upload were working last I tested it. I haven't run in the past couple months. Are you getting errors or ?

**Comment by fatmaindikass** [comment]
I want to turn off someone's Instagram. but don't have email and password. Can it?

Dikirim dari iPhone saya

**Comment by eddyizm** [comment]
You clearly did not read, look, or even attempt to download the code. This whole repository is for usage on your own account not someone else's.
